POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyMTIwMjYzZTAzZDExZTc2MTk3NGMyZSIsImlhdCI6MTY0NTQ3MTA3OCwiZXhwIjoxNjQ1NDcxMTM4fQ.bGi-0rTxcj-jcCxzld_BCF_wHEtXG-_TROEZGa_ah6I

{
  "title": "Blogin lisääminen mahdollista vain tokenilla",
  "author": "Tehtävä 4.19",
  "url": "www.fi",
  "likes": 1
}