POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Jokin käyttäjä kolmannen blogin kirjoittajaksi, populointi",
  "author": "Tehtävä 4.17",
  "url": "www.fi",
  "likes": 3
}